### PR TITLE
Fix "Go back" action

### LINKED ISSUE #1: Going back in history after following symlink is recursive
When traversing history back going to the symlink causes the symlink to follow again causing an infinite loop. Mainly affects people using the auto follow option.

Ideas:
1. Remove history. Not sure if there's an API for that
2. Detect going back and don't follow symlink

### PR DESCRIPTION
**Pull request by vient**
I thought that it will be easier to write my own version than to understand #5 and problem described in it (so I don't know if my version has this problem as well or not).

Works based on assumption that you've accepted symlink redirection if you had real file opened right after symlink to it.

Fixes #1, #5

### CODE REVIEW

**Comment by vient** [comment]
^ I'm used to "squash and rename" style of merging where commit number and their names in branch do not matter.

**Comment by zaucy** [comment]
Just reword the commit message with a `fix: ` prefix and it'll go away (I can do it for you if you'd like)

Also I setup a changelog automatic generator so don't worry about incrementing the version or adding to the changelog.

File: src/extension.ts [hunk 1]
```diff
@@ -21,8 +21,15 @@ export function activate(context: vscode.ExtensionContext) {
 				return;
 			}
 
-			// Not a symlink. No need to open real path.
 			if (filePath === realFilePath) {
+				// Not a symlink. No need to open real path.
+				lastRealFilePath = realFilePath;
+				return;
+			}
+			if (lastRealFilePath === realFilePath) {
```
Comment (zaucy) [inline src/extension.ts]: I tested this on my Windows machine and the file paths do not match. There's something up with the casing with these two variables causing them to be different.

Comment (zaucy) [reply src/extension.ts]: I'm fine merging this in without handling this. I'll just make a windows specific gh issue. But if you have an idea I'm all ears!

I tried `fs.realpath.native` to see if that made a difference, but it caused some very strange behaviour that I cannot debug at the moment.

Comment (vient) [reply src/extension.ts]: Yeah, I have an idea: issue `fs.stat` additionally and compare tuples `(stats.ino, stats.dev)`
Trying to write it now in the most async typescript way possible 😄

**Comment by vient** [comment]
Please check if it works for you now.

File: src/extension.ts (hunk 1 above)
Comment (vient) [reply src/extension.ts]: Please check if it works for you now.

Comment (zaucy) [reply src/extension.ts]: no dice :[

lets revert the fs stat change and I'll add a gh issue detailing the problem for Windows. That way macOS and linux users can still benefit.

Comment (vient) [reply src/extension.ts]: I first tested another version that compared stat fields one by one, then force pushed slightly better version that seems to be broken because you cannot compare arrays with `===`. Sorry, my first time writing TypeScript 😅

Comment (vient) [reply src/extension.ts]: Please try once more
Now I checked that it works with Windows symlinks, albeit opened from WSL.

If it still does not work, reverting fs.stat commit and making a separate issue sounds good.

**Comment by vient** [comment]
If you try to open symlink from the file which is this symlink's destination, my code thinks that it was a "Go back" action, goes back and ends up in the right file.
This is fine but there is a little side effect: afterwards you have "go forward" available because for VSCode we opened file than immediately went back. If only there was a way to remove entries from file history...

File: src/extension.ts (hunk 1 above)
Comment (zaucy) [reply src/extension.ts]: the go back is working!

**Comment by zaucy** [comment]
It's working! I think this is an improvement as is, so lets merge it.

I too wish there was a history API. I looked into it for a bit, but didn't find anything.

**Comment by zaucy** [comment]
also @vient you don't have to squash force push everytime! I'll let github squash it for you and give it the appropriate prefix so the changelog updates :)

**Review by zaucy — APPROVED** [review]

**Comment by zaucy** [comment]
unless you were just renaming after commiting without the prefix. If that's the case then my bad!

**Comment by zaucy** [comment]
@vient Thanks for all your contributions! `1.0.3` with your changes should be on the vscode extension marketplace any moment :)
